name: Build README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '30 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python3 -m pip install -U codingame[async]
    - name: Update README
      run: |-
        python readme_builder.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "laafilal@student.1337.ma"
        git config --global user.name "laafilal"
        git config --global credential.helper store
        git add -A
        git commit -m "Codingame stats Updated" || exit 0
        git push
